### ISSUE TITLE
Change the Position of the Settings Button

### ISSUE THREAD

**Issue by DefinitelyNotAnAssassin** [Finestwork/my-schema-flow#13]
The settings button are not easily detectable on its current location. Consider putting it beside the left toolbar icons.

![image](https://github.com/Finestwork/my-schema-flow/assets/46719110/eefc4403-9ee6-4067-8878-d8503352eaad)

**Comment by Finestwork** [comment]
Hello, @DefinitelyNotAnAssassin! Actually, I was attempting to imitate the title bar of vscode. The idea is to differentiate the controls specifically for the canvas from those for general use. Hmmmm, I'm still not sure if additional controls will be added to the toolbar, such as hiding the left or right panels.


![image](https://github.com/Finestwork/my-schema-flow/assets/62718854/6625f515-7e25-483a-9d14-7c60fc358132)
